export const getPlayersForGameData = (team, player) => ({
  _id: player._id,
  full: player.name.full,
  time_in_game: '21:12',
  team: team._id,
  number: player.number,
  stats: {
    game_played: player.stats.game_played,
    game_started: player.stats.game_started,
    points: {
      total: 0,
      global: player.stats.points.total,
      isTouched: false,
    },
    rebound: {
      defence: {
        total: 0,
        global: player.stats.rebound.offence.total,
        isTouched: false,
      },
      offence: {
        total: 0,
        global: player.stats.rebound.defence.total,
        isTouched: false,
      },
    },
    assists: {
      total: 0,
      global: player.stats.assists.total,
      isTouched: false,
    },
    steals: {
      total: 0,
      global: player.stats.steals.total,
      isTouched: false,
    },
    blocks: {
      total: 0,
      global: player.stats.blocks.total,
      isTouched: false,
    },
    turnover: {
      total: 0,
      global: player.stats.turnover.total,
      isTouched: false,
    },
    fouls: {
      take: {
        total: 0,
        global: player.stats.fouls.take.total,
        isTouched: false,
      },
      give: {
        total: 0,
        global: player.stats.fouls.give.total,
        isTouched: false,
      },
    },
    FT: {
      total: 0,
      globalMade: player.stats.FT.made,
      isTouchedMade: false,
      made: 0,
      global: player.stats.FT.total,
      isTouched: false,
    },
    two_points: {
      total: 0,
      globalMade: player.stats.two_points.made,
      isTouchedMade: false,
      made: 0,
      global: player.stats.two_points.total,
      isTouched: false,
    },
    three_points: {
      total: 0,
      globalMade: player.stats.three_points.made,
      isTouchedMade: false,
      made: 0,
      global: player.stats.three_points.total,
      isTouched: false,
    },
    zones: {
      paint: {
        total: 0,
        globalMade: player.stats.zones.paint.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.paint.total,
        isTouched: false,
      },
      left_two: {
        total: 0,
        globalMade: player.stats.zones.left_two.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.left_two.total,
        isTouched: false,
      },
      right_two: {
        total: 0,
        globalMade: player.stats.zones.right_two.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.right_two.total,
        isTouched: false,
      },
      left_two_45deg: {
        total: 0,
        globalMade: player.stats.zones.left_two_45deg.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.left_two_45deg.total,
        isTouched: false,
      },
      right_two_45deg: {
        total: 0,
        globalMade: player.stats.zones.right_two_45deg.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.right_two_45deg.total,
        isTouched: false,
      },
      center_two: {
        total: 0,
        globalMade: player.stats.zones.center_two.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.center_two.total,
        isTouched: false,
      },
      left_three: {
        total: 0,
        globalMade: player.stats.zones.left_three.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.left_three.total,
        isTouched: false,
      },
      right_three: {
        total: 0,
        globalMade: player.stats.zones.right_three.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.right_three.total,
        isTouched: false,
      },
      left_three_45deg: {
        total: 0,
        globalMade: player.stats.zones.left_three_45deg.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.left_three_45deg.total,
        isTouched: false,
      },
      right_three_45deg: {
        total: 0,
        globalMade: player.stats.zones.right_three_45deg.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.right_three_45deg.total,
        isTouched: false,
      },
      center_three: {
        total: 0,
        globalMade: player.stats.zones.center_three.made,
        isTouchedMade: false,
        made: 0,
        global: player.stats.zones.center_three.total,
        isTouched: false,
      },
    },
  },
});
